#pragma once
#define FUNC_AND 0
#define FUNC_EOR 1
#define FUNC_ORR 2
#define FUNC_TST 3
#define FUNC_TEQ 4
#define FUNC_CMP 5
#define FUNC_CMN 6
#define FUNC_ADD 7
#define FUNC_SUB 8
#define FUNC_ADC 9
#define FUNC_RSB 10
#define FUNC_SBC 11 
#define FUNC_MVN 12
#define FUNC_LSL 13
#define FUNC_ASR 14
#define FUNC_RRX 15
#define FUNC_ROR 16
#define FUNC_BSWP 17
#define FUNC_SWR 18
#define FUNC_UADDPB 19
#define FUNC_UADDPH 20
#define FUNC_UADDPW 22 
#define FUNC_SADDPB 23 
#define FUNC_SADDPH 24
#define FUNC_SADDPW 25
#define FUNC_VADDPB 26
#define FUNC_VADDPH 27
#define FUNC_VSADDB 28
#define FUNC_VSADDH 29