#define INSY_CODE    0
#define IN_CODE      1
#define OUTSY_CODE   2
#define OUT_CODE     3
#define SFL_CODE     4
#define LFL_CODE     5
#define SMF_CODE     6
#define SINT_CODE    7
#define BINT_CODE    8
#define UINT_CODE    9
#define CINT_CODE    10
#define INT_CODE     11