#pragma once
#define ADD_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SADD_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define AND_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SAND_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define EOR_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SEOR_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define ORR_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SORR_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define TSTTEST_INSTR 0xFFFFFFFFFFFFFFFF

#define TEQ_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define CMP_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define CMN_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define SUB_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SSUB_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define ADC_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SADC_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define RSB_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SRSB_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define SBC_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SSBC_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define MVN_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SMVN_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define LSR_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SLSR_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define ASR_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SASR_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define RRX_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SRRX_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define ROR_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SROR_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define BSWP_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SBSWP_TEST_INSTR 0xFFFFFFFFFFFFFFFF

#define SWR_TEST_INSTR 0xFFFFFFFFFFFFFFFF
#define SSWR_TEST_INSTR 0xFFFFFFFFFFFFFFFF